chore(): update husky script
nestjs/schematics pull request #1044
Opened 2022-05-20 11:48 UTC by Tony133

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/nestjs/nest/blob/master/CONTRIBUTING.md
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?
Update husky script

## Does this PR introduce a breaking change?
- [ ] Yes
- [x] No

## Other information

2022-05-20 16:47 UTC, micalevisk requested changes
as we're using `lint-staged`, I believe that we should have a configuration entry for it on `package.json`. See https://github.com/nestjs/docs.nestjs.com/pull/2314

Also, I'm getting these warnings:

```
hint: The '.husky/pre-commit' hook was ignored because it's not set as executable.
hint: You can disable this warning with `git config advice.ignoredHook false`.
hint: The '.husky/commit-msg' hook was ignored because it's not set as executable.
hint: You can disable this warning with `git config advice.ignoredHook false`.
```

2022-05-20 17:11 UTC, Tony133 commented
Yeah, I added it now in the package.json

2022-05-20 17:13 UTC, micalevisk commented
I believe you should do `chmod +x .husky/pre-commit && chmod +x .husky/commit-msg`

2022-05-20 17:16 UTC, Tony133 commented
Done! now it should be ok 👍

2022-05-20 17:17 UTC, micalevisk approved these changes
it worked now! :heart:

2022-05-22 02:24 UTC, micalevisk commented on package.json
> +    "packages/**/*.{ts,json}": []
```suggestion
    "**/*.{ts,json}": []
```

2022-05-22 08:23 UTC, Tony133 commented on package.json
> +    "packages/**/*.{ts,json}": []
Done! I have updated the `package.json`

2022-05-23 06:31 UTC, merged